from enum import Enum


class ErrorCode(str, Enum):
    """Machine-readable error codes for contract and adapter checks."""

    E_SCHEMA_VALIDATION = "E_SCHEMA_VALIDATION"
    E_PARAM_INVALID = "E_PARAM_INVALID"
    E_GH_EXECUTION_FAILED = "E_GH_EXECUTION_FAILED"
    E_ARTIFACT_MISSING = "E_ARTIFACT_MISSING"
    E_COORD_MAPPING_FAILED = "E_COORD_MAPPING_FAILED"
    E_SELECTION_INVALID = "E_SELECTION_INVALID"
    E_CONTRACT_INCONSISTENT = "E_CONTRACT_INCONSISTENT"
